
export const navConfig = {
    candidate: [
        { label: "Dashboard", href: "/candidate", icon: "LayoutDashboard" },
        { label: "Assigned Course", href: "/courses", icon: "BookOpen" },
        { label: "Tests", href: "/tests", icon: "ClipboardList" },
        { label: "Results", href: "/results", icon: "Award" },
        { label: "Notifications", href: "/notifications", icon: "Bell" },
    ],
    learner: [
        { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
        { label: "Roadmap", href: "/roadmap", icon: "Map" },
        { label: "Courses", href: "/courses", icon: "BookOpen" },
        { label: "Tests", href: "/tests", icon: "ClipboardList" },
        { label: "Learning Tracker", href: "/tracker", icon: "Clock" },
        { label: "Reflections", href: "/reflections", icon: "Notebook" },
        { label: "Skill Map", href: "/skills", icon: "Brain" },
        { label: "Certificates", href: "/certificates", icon: "Award" },
        { label: "Results", href: "/results", icon: "Award" },
        { label: "Feedback", href: "/feedback", icon: "MessageSquare" },
        { label: "Notifications", href: "/notifications", icon: "Bell" },
    ],
    supervisor: [
        { label: "Dashboard", href: "/supervisor", icon: "LayoutDashboard" },
        { label: "Grading", href: "/supervisor", icon: "ShieldCheck" },
        { label: "Progress", href: "/supervisor/progress", icon: "BarChart3" },
        { label: "Assign Courses", href: "/supervisor/assign-courses", icon: "BookOpen" },
        { label: "Roadmap", href: "/roadmap", icon: "Map" },
        { label: "Courses", href: "/courses", icon: "BookOpen" },
        { label: "Tests", href: "/tests", icon: "ClipboardList" },
        { label: "Learning Tracker", href: "/tracker", icon: "Clock" },
        { label: "Reflections Review", href: "/supervisor/reflections", icon: "Notebook" },
        { label: "Skill Map", href: "/skills", icon: "Brain" },
        { label: "Certificates", href: "/certificates", icon: "Award" },
        { label: "Feedback", href: "/feedback", icon: "MessageSquare" },
        { label: "Notifications", href: "/notifications", icon: "Bell" },
    ],
    admin: [
        { label: "Dashboard", href: "/admin/dashboard", icon: "ShieldCheck" },
        { label: "User Management", href: "/admin/users", icon: "Users" },
        { label: "Archetypes", href: "/admin/archetypes", icon: "Layers" },
        { label: "Roadmaps", href: "/admin/roadmaps", icon: "Map" },
        { label: "Course Management", href: "/admin/courses", icon: "BookOpen" },
        { label: "Test Management", href: "/admin/tests", icon: "ClipboardList" },
        { label: "Analytics", href: "/admin/analytics", icon: "BarChart3" },
        { label: "Audit Logs", href: "/admin/audit", icon: "FileText" },
        { label: "Skill Search", href: "/admin/skills", icon: "Brain" },
        { label: "Certificate Registry", href: "/admin/certificates", icon: "Award" },
        { label: "Supervisor Hub", href: "/supervisor", icon: "LayoutDashboard" },
    ],
};
